name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: europe-west1
  SERVICE_NAME: monorepo

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout
#        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Get Secrets
      - id: secrets
        uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
        with:
          secrets: |-
            dbUrl:projects/526232931256/secrets/MARIA_DB_URL_PROD/versions/1

      # Build and push image to Google Container Registry
#      - name: Build
#        run: |-
#          echo Image Name: "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
#          gcloud builds submit \
#            --quiet \
#            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        env:
          MARIA_DB_URL: ${{ steps.secrets.outputs.dbUrl }}
        run: |-
          echo DbURL=${{ steps.secrets.outputs.dbUrls }}
          echo MDB=$MARIA_DB_URL
          gcloud run deploy "$SERVICE_NAME" \
            --region "$RUN_REGION" \
            --image "gcr.io/mardb1/monorepo@sha256:6b90f3cd9b87939e38179f55cfb1bc196fc67e08f1974baffcc45a5b8f9feeb6" \
            --platform "managed" \
            --allow-unauthenticated \
#            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
#             --quiet \
